# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ba2a17832014e3034995de5f7def76a4e0437acdf66ce93e3fccb257f03ab65db63b22ef697d6f4d4af09adeb339af1ff631ee3543a783659be7109d626d7ba

test:
  secret_key_base: 7da599654bad22a0059b8429d580eca7dc9bdfa5789e14385fb31bd5ef5fd8f443f62de8bbe161f4111250b2b655253a9bc4d4b5c74986d172a60b5fe599964e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
